### ISSUE TITLE
Timeout error when rapidly connecting and disconnecting

### ISSUE THREAD

**Issue by rudyjantz** [nats-io/cnats#154] opened 2018-07-31 12:08 UTC
Hi cnats folks,

I use the cnats library to connect multiple C clients to gnatsd, and sometimes my connections fail. To demonstrate it, I've created a simple test case that connects and disconnects in a tight loop. I'm currently using v1.7.6. The test fails for that version. I've also tried this test on master (latest commit 4a0968781888645f5075856f1cfcbb4a8f7d42e2), and it fails there as well.

I've attached the test. Please take a look, and thanks for your time.

[flutter-nats.tar.gz](https://github.com/nats-io/cnats/files/2245202/flutter-nats.tar.gz)

**Comment by kozlovic** [comment] 2018-07-31 16:01
I can't reproduce the problem on a macOS and Ubuntu VM, not sure which OS you are running this on.

I suspect that it may be due to the fact that you have sockets accumulating in TIME_WAIT state. While running your test program, run `netstat -an | grep TIME_WAIT | wc` and see if this number grows. It does not in my case.

**Comment by kozlovic** [comment] 2018-07-31 16:11
I take the comment above back. I did not use your test program so I did not get any issue. Your test program is wrong. You have an array of connection and options points, but call flutter_connect with those pointers (uninitialized), and then call `natsConnection_Connect(&conn)` on that.. this is wrong. You end-up creating but not closing the connections..

Here is a corrected version that works fine:
```
static
void flutter_conn_closed_cb(natsConnection  *nc, void *null)
{
        printf("flutter_conn_closed_cb(): nc(%p)\n", (void*) nc);
}

int flutter_connect(natsConnection **newConn, natsOptions **newOpts)
{
        natsStatus s;
        natsOptions *opts = NULL;
        natsConnection *conn = NULL;

        s  = NATS_OK;
        printf("Before options create: %s(%d)\n", natsStatus_GetText(s), s);
        s |= natsOptions_Create(&opts);
        printf("Before set closed cb: %s(%d)\n", natsStatus_GetText(s), s);
        s |= natsOptions_SetClosedCB(opts, flutter_conn_closed_cb, NULL);
        printf("Before set url: %s(%d)\n", natsStatus_GetText(s), s);
        s |= natsOptions_SetURL(opts, "nats://localhost:4222");

        printf("Before if check: %s(%d)\n", natsStatus_GetText(s), s);
        if(s){
                printf("Error setting options. " \
                       "error value or'd across all options calls: %s(%d)\n",
                       natsStatus_GetText(s), s);
                return 1;
        }

        s = natsConnection_Connect(&conn, opts);
        if(s){
                printf("Error creating connection: %s(%d)\n",
                             natsStatus_GetText(s), s);
                return 1;
        }
        *newConn = conn;
        *newOpts = opts;
        return 0;
}

int flutter_destroy(natsConnection *conn, natsOptions *opts)
{
        natsOptions_Destroy(opts);
        natsConnection_Destroy(conn);
        return 0;
}

int main(void)
{
        int i;
        while(1){
            for(i = 0; i < NUM_CONNS; i++){
                //printf("connnecting\n");
                if(flutter_connect(&conn_arr[i], &opts_arr[i])){
                        return 1;
                }
            }
            for(i = 0; i < NUM_CONNS; i++){
                //printf("destroying\n");
                if(flutter_destroy(conn_arr[i], opts_arr[i])){
                        return 1;
                }
            }
        }
        printf("successful\n");

        return 0;
}
```

**Closed by kozlovic** 2018-07-31 16:11 UTC

**Comment by rudyjantz** [comment] 2018-07-31 16:39
@kozlovic Yes, you're right. This test case is nonsense. Thanks for checking it.

**Comment by kozlovic** [comment] 2018-07-31 16:41
@rudyjantz Glad there was no actual issue with the library :-)
