### ISSUE TITLE
Working nats_JSONParse function depends of Windows locale settings

### ISSUE THREAD

**Issue by PaulEU** [nats-io/cnats#105] opened 2017-10-11 21:29 UTC
nats_JSONParse function doesn't work if Windows locale settings for decimal symbol is comma.

_jsonGetNum takes number ("port":4222,) with comma, but should without.

**strtold** function gets locale settings. Probably should be used _strtold_l function with constant english locale settings.

My JSON file:
{"server_id":"Ehv4Cv12sdLR51ETe8EYYV","version":"1.0.4","go":"go1.8.3","host":"0.0.0.0","port":**4222,**"auth_required":false,"ssl_required":false,"tls_required":false,"tls_verify":false,"max_payload":1048576}

![image](https://user-images.githubusercontent.com/6093796/31467416-2ebeeeca-aeda-11e7-89d2-b1539eef05cb.png)

**Comment by kozlovic** [comment] 2017-10-11 22:13
@PaulEU Thank you for the report. Although I agree with the statement, I am unable to reproduce if I change the format or the locale. Anything special I need to do to be able to reproduce?

**Comment by kozlovic** [comment] 2017-10-11 22:45
@PaulEU I was able to reproduce only if I explicitly call `setlocale(x, y)` directly in the library/app, not from the control panel. I will investigate. Thanks!

**Comment by kozlovic** [comment] 2017-10-12 01:51
Just to update you that I will work on this tomorrow. In the meantime, I have just merged PR #106 which solves an issue I discovered when reproducing the parsing issue.

**Comment by PaulEU** [comment] 2017-10-12 08:27
I have "Polish (Poland)" Format selected (in combobox) in the Regional and Language settings in the Control Panel. Reproducing by calling setlocale(x, y) is also correct gives the same effect.

**Comment by kozlovic** [comment] 2017-10-12 23:16
@PaulEU Would appreciate if you could check that PR #108 solves the issue for you. Thanks!

**Comment by PaulEU** [comment] 2017-10-13 19:30
I tested. Now, it works properly. Thanks!

**Closed** 2017-10-13 20:05 UTC
Labels: waffle:needs review

**Comment by kozlovic** [comment] 2017-10-13 20:07
@PaulEU Thank you for checking! The PR has been merged.

**Comment by qwertzui11** [comment] 2017-11-16 11:06
there are still issues with the local and the json parsing.
eg `natsConnection_ConnectTo` won't work if the executable got called with `LC_ALL=de_AT.utf8 ./my_test_executable`
OS: Ubuntu 17.04
dependencies for local: `apt install language-pack-de`
if the `LC_ALL` gets set to `de_DE.utf8` or `en_US.utf8` things do work.

**Comment by kozlovic** [comment] 2017-11-16 16:11
I cannot reproduce this issue from master branch. Are you sure you are not using a release build (1.7.2 or earlier)? If you confirm that you did not run from master, I may issue a release (1.7.4) soon with this fix and some others.

**Comment by kozlovic** [comment] 2017-11-16 16:36
@qwertzui11 I take that back. Will look into it. Thanks!

**Comment by kozlovic** [comment] 2017-11-17 01:46
@qwertzui11 Could you please check with code from PR #118 and see if that resolves the issue for you?

**Comment by qwertzui11** [comment] 2017-11-17 13:29
yes the PR branch resolves the problem. I tested 
- en_US.utf8
- de_AT.utf8
- de_DE.utf8
thx a lot for your effort! :+1: :smiley:

**Comment by kozlovic** [comment] 2017-11-17 15:13
@qwertzui11 Thanks for the confirmation, I will issue a release soon.
